import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 20,
      description: 'A Popular Shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 55,
      brand: 'Tomy Hilfiger',
      rating: 4,
      numOfReviews: 7,
      countInStock: 25,
      description: 'A Popular Fit Shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 20,
      description: 'A Popular Shirt',
    },
    {
      name: 'Golf Pant',
      slug: 'golf-pant',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 99,
      brand: 'Polo',
      rating: 5,
      numOfReviews: 30,
      countInStock: 15,
      description: 'A Popular Fit Pant',
    },
    {
      name: 'Fit Pant',
      slug: 'fit-pant',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 89,
      brand: 'Zara',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 20,
      description: 'A Popular slim fit Pant',
    },
    {
      name: 'Classic Pant',
      slug: 'classic-pant',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 89,
      brand: 'Casely',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 20,
      description: 'A Popular classic Pant',
    },
  ],
};

export default data;
